---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }} 
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.containerPort }}
          volumeMounts:
          - name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
            mountPath: /etc/nginx/{{ .Values.nginxConf }}
            subPath: {{ .Values.nginxConf }}
            readOnly: true
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
            items:
              - key: {{ .Values.nginxConf }}
                path: {{ .Values.nginxConf }} 